export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const POST_PRODUCT = "POST_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CITIES = 'GET_CITIES';
export const GET_PRODUCTS_BY_LOCATION = 'GET_PRODUCTS_BY_LOCATION'
export const USER_PRODUCTS = 'USER_PRODUCTS'
